# Jekyll configuration
encoding: 'utf-8'
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
paginate: 50 # it will paginate after this number
paginate_path: /page:num/
language: 'en-uk'
words_per_minute: 200

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: Adev42
description: Learning is an endless journey
cover: assets/images/blog-cover3.jpeg
logo: assets/images/blog-icon-200.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
CNAME: #add cname for website to be created

# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,
subscribe: True
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
linkedin: tienduy-nguyen
twitter: tienduy_nguyen # replace by your username
facebook: # replace by your username

# Disqus
disqus: False
disqus_shortname: jekyller # replace with your disqus username

# Alternative comment to replace Disque
# Gitalk: https://github.com/gitalk/gitalk
gitalk:
  # Note: A GitHub Application is needed for authorization, if you don't have one, going to https://github.com/settings/applications/new register a new one.
  # You must specify the website domain url in the Authorization callback URL field.
  isUsed: True
  clientID: <Add code here> # GitHub Application Client ID
  clientSecret: <Add code here> # GitHub Application Client Secret,
  repo: tienduy-nguyen # Storage gittalk's repository
  owner: tienduy-nguyen # GitHub repo owner,
  admin: tienduy-nguyen # GitHub repo owner and collaborators, only these guys can initialize github issues eg. 'colynn,daattali'

# Google Analytics
google_analytics: G-DFDQFLJDFMJ # replace with your GA tracking identifier

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
# plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-gist, jekyll-feed, jemoji, jekyll-include-cache]
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-environment-variables
  - slugify
  - jekyll-remote-theme
  - github-pages

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

feed:
  path: feed.xml
  # Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for building master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
username: tienduy-nguyen
repo: blog
branch: master
relative_source: ../blog/
destination: ../gh-pages/
production_url: https://blog.adev42.com/
source_url: https://github.com/tienduy-nguyen/blog/

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - '*.Rmd'
  - .git*
  - vendor

# Defaults
defaults:
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      read_time: true
      toc: true
      toc_label: 'Menu'
      toc_icon: 'file-alt'
      comments: true # true
      share: true
      related: true
      autoads: true
      class: post-template
      subclass: 'post'
      author: tienduy
      navigation: True
      current: post
